[tool.ruff]
line-length = 100

[tool.ruff.lint]
select=["I"]
extend-ignore=["ANN", "D", "FBT", "FIX", "PLR", "TD", "UP"]
ignore=[
    "B904",
    "C901",
    "COM812",
    "E501", "E721",
    "EM102",
    "F541",
    "FA102",
    "G004",
    "PD901",
    "PERF203", "PERF401",
    "PLR2004",
    "PLW2901",
    "RET504",
    "RUF003", "RUF005",
    "S101", "S602",
    "SIM401",
    "SLF001",
    "T201",
    "TRY003",
]
